# Generated by Django 5.1.4 on 2024-12-24 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevo_sites', '0003_sitearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sevo_sites.article'),
        ),
        migrations.DeleteModel(
            name='SiteArticle',
        ),
    ]
