# Generated by Django 5.1.4 on 2024-12-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevo_sites', '0004_site_article_delete_sitearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='order',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Order'),
        ),
    ]
