# Generated by Django 5.1.4 on 2025-01-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevo_sites", "0006_alter_site_options_site_subsites_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="allow_subsites",
            field=models.BooleanField(default=False),
        ),
    ]
