# Generated by Django 5.1.4 on 2025-01-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevo_sites", "0007_site_allow_subsites"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
