# Generated by Django 5.1.4 on 2025-01-10 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sevo_sites", "0009_subsite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subsite",
            old_name="site",
            new_name="mastersite",
        ),
    ]
