# Generated by Django 5.1.4 on 2025-01-11 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sevo_sites", "0011_alter_subsite_subsite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subsite",
            options={"ordering": ["order"]},
        ),
    ]
