# Generated by Django 5.1.4 on 2025-01-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevo_sites", "0012_alter_subsite_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="allow_subsites",
        ),
        migrations.RemoveField(
            model_name="site",
            name="subsites",
        ),
        migrations.AlterField(
            model_name="site",
            name="meta_description",
            field=models.TextField(
                blank=True, max_length=160, null=True, verbose_name="Meta Description"
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="meta_keywords",
            field=models.TextField(
                blank=True, max_length=160, null=True, verbose_name="Meta Keywords"
            ),
        ),
    ]
