# Generated by Django 5.1.4 on 2024-12-24 20:52

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevo_media', '0005_alter_filetag_options'),
        ('sevo_sites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('menu_type', models.CharField(choices=[('MAIN', 'Main'), ('META', 'Meta'), ('NONE', 'None')], default='Main', max_length=10)),
                ('meta_keywords', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Keywords')),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description')),
                ('url_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL Path')),
                ('is_reverse', models.BooleanField(default=False, verbose_name='Is Reverse')),
                ('published', models.BooleanField(default=True, verbose_name='Published')),
                ('is_home', models.BooleanField(default=False, verbose_name='Is Home')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sevo_media.picture', verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
            },
        ),
    ]
