# Generated by Django 5.1.4 on 2024-12-24 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevo_sites', '0002_remove_article_slug_alter_article_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sevo_sites.article', verbose_name='Article')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sevo_sites.site')),
            ],
        ),
    ]
