# Generated by Django 5.1.4 on 2025-01-11 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevo_sites2", "0002_article_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="site2article",
            name="published",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="site2article",
            name="site2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_articles",
                to="sevo_sites2.site2",
            ),
        ),
    ]
