# Generated by Django 5.1.4 on 2025-01-11 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevo_sites2", "0003_site2article_published_alter_site2article_site2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "menu_type",
                    models.CharField(
                        choices=[
                            ("PRIMARY", "Primary"),
                            ("SECOMDARY", "Secondary"),
                            ("META", "Meta"),
                            ("OTHER", "Other"),
                        ],
                        default="Primary",
                        max_length=50,
                        verbose_name="Menu Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menues",
            },
        ),
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "Article", "verbose_name_plural": "Articles"},
        ),
        migrations.AlterModelOptions(
            name="site2article",
            options={
                "verbose_name": "Site2Article",
                "verbose_name_plural": "Site2Articles",
            },
        ),
        migrations.AlterField(
            model_name="site2article",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sevo_sites2.article",
                verbose_name="Article",
            ),
        ),
        migrations.AlterField(
            model_name="site2article",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="site2article",
            name="published",
            field=models.BooleanField(default=True, verbose_name="Published"),
        ),
        migrations.AlterField(
            model_name="site2article",
            name="site2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="site_articles",
                to="sevo_sites2.site2",
                verbose_name="Site2",
            ),
        ),
        migrations.CreateModel(
            name="MenuSite2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("published", models.BooleanField(default=True)),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_sites",
                        to="sevo_sites2.menu",
                        verbose_name="Menu",
                    ),
                ),
                (
                    "site2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sites",
                        to="sevo_sites2.site2",
                        verbose_name="Site2",
                    ),
                ),
                (
                    "subsites2",
                    models.ManyToManyField(
                        blank=True,
                        related_name="subsites",
                        to="sevo_sites2.site2",
                        verbose_name="Subsites2",
                    ),
                ),
            ],
            options={
                "verbose_name": "MenuSite2",
                "verbose_name_plural": "MenuSites2",
            },
        ),
    ]
