# Generated by Django 5.1.4 on 2025-01-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevo_sites2", "0005_alter_menu_options_article_css_class_article_css_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="css_class",
        ),
        migrations.RemoveField(
            model_name="article",
            name="css_id",
        ),
        migrations.AddField(
            model_name="site2article",
            name="css_class",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="CSS Classes"
            ),
        ),
        migrations.AddField(
            model_name="site2article",
            name="css_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="CSS ID"
            ),
        ),
    ]
