# Generated by Django 5.1.4 on 2025-01-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevo_sites2", "0006_remove_article_css_class_remove_article_css_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="css_class",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="CSS Classes"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="css_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="CSS ID"
            ),
        ),
    ]
