# Generated by Django 5.1.4 on 2025-01-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevo_sites2", "0007_article_css_class_article_css_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menusite2",
            options={
                "verbose_name": "Menu Site 2",
                "verbose_name_plural": "Menu Sites 2",
            },
        ),
        migrations.AlterModelOptions(
            name="site2",
            options={
                "ordering": ["order"],
                "verbose_name": "Site 2",
                "verbose_name_plural": "Sites 2",
            },
        ),
        migrations.AlterModelOptions(
            name="site2article",
            options={
                "verbose_name": "Site 2 Article",
                "verbose_name_plural": "Site 2 Articles",
            },
        ),
        migrations.AddField(
            model_name="site2",
            name="css_class",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="CSS Classes"
            ),
        ),
    ]
