# Generated by Django 5.1.4 on 2025-01-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevo_sites2", "0008_alter_menusite2_options_alter_site2_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menusite2",
            options={
                "verbose_name": "Menu Site2",
                "verbose_name_plural": "Menu Sites2",
            },
        ),
        migrations.AlterModelOptions(
            name="site2",
            options={
                "ordering": ["order"],
                "verbose_name": "Site2",
                "verbose_name_plural": "Sites2",
            },
        ),
        migrations.AlterModelOptions(
            name="site2article",
            options={
                "verbose_name": "Site2 Article",
                "verbose_name_plural": "Site2 Articles",
            },
        ),
        migrations.AlterField(
            model_name="menu",
            name="menu_type",
            field=models.CharField(
                choices=[
                    ("PRIMARY", "Primary"),
                    ("SECONDARY", "Secondary"),
                    ("META", "Meta"),
                    ("OTHER", "Other"),
                ],
                default="Primary",
                max_length=50,
                verbose_name="Menu Type",
            ),
        ),
    ]
